[package]
name = "progetto_pds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
chrono = "0.4.26"
image = "0.24.6"
screenshots = "0.6.0"
show-image = "0.13.1"
thiserror = "1.0.43"
