[package]
name = "progetto_pds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
screenshots = "0.6.0"
show-image = "0.13.1"
